project:
  type: website
  output-dir: docs
editor:
  render-on-save: true

website:
  title: "Climate change and natural disasters"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: descriptives.qmd
        text: Descriptives
      - href: analyse.qmd
        text: Analyse

format:
  html:
    theme: cosmo
    toc: true
